FROM com.gft.deuba.unity.release-1.fe-weather:build

ARG GITHASH
ARG TIMESTAMP
ARG COMPONENT

ENTRYPOINT [ "/opt/fe-weather", "--staticdir", "/workdir/static", "--templatefile", "/workdir/index.html", "--version", "3.0.0" ]
