##############################################################################
---

apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: com-gft-officeday-istio-testing-in-production
  labels:
    PROJECT: com.gft.officeday.istio.testing-in-production
    app: frontend
    version: "1.0.0"
spec:
  containers:
    - name: frontend
      image: com.gft.officeday.istio.testing-in-production.frontend.fe-weatherstation:v1
      imagePullPolicy: Never
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
      - name: config
        mountPath: "/usr/share/nginx/html/assets/config.json"
        readOnly: true
        subPath: api.Url
  volumes:
    - name: config
      configMap:
        name: frontend-api-config
