##############################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: random-destination
  namespace: com-gft-officeday-istio-testing-in-production
  labels:
    PROJECT: com.gft.officeday.istio.testing-in-production
    app: random
    version: "1.0.0"

spec:

  host: random
  
  subsets:

  - name: prod
    labels:
      version: "1.0.0"

  - name: pre-prod
    labels:
      version: "1.0.0"
