FROM node:lts-alpine

COPY src/angular/fe-weatherstation /opt/fe-weatherstation/
WORKDIR /opt/fe-weatherstation

RUN npm install
RUN npm install -g @angular/cli

EXPOSE 8080

CMD [ "ng", "serve", "--host", "0.0.0.0", "--port", "8080", "--live-reload" ]
