##############################################################################
---

apiVersion: v1
kind: Service
metadata:
  name: thermometer
  namespace: com-gft-officeday-istio-testing-in-production
  labels:
    PROJECT: com.gft.officeday.istio.testing-in-production
    app: thermometer
spec:
  selector:
    PROJECT: com.gft.officeday.istio.testing-in-production
    app: thermometer
    version: 1.0.0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      appProtocol: http
      name: http-endpoint
