##############################################################################
---

apiVersion: v1
kind: Service
metadata:
  name: random
  namespace: com-gft-officeday-isio-testing-in-production-1
  labels:
    PROJECT: com.gft.officeday.isio.testing-in-production-1
    app: random

spec:

  selector:
    PROJECT: com.gft.officeday.isio.testing-in-production-1
    app: random
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      appProtocol: http
      name: http-endpoint
